/** @typedef {{ slug: string, title: string, image: string, sampleTags: string[], popular?: boolean }} HashtagCategory */

/**
 * Image files live in public/hashtag-categories/ and are generated via:
 * npm run generate:category-images
 *
 * Photo mapping is defined in scripts/category-photo-sources.mjs.
 * TODO: Replace procedural color-theme sources (black, red, white, green, pink, christmas)
 * with dedicated photo assets when available.
 */

function category(slug, title, sampleTags, popular = false) {
  return {
    slug,
    title,
    image: `/hashtag-categories/${slug}.webp`,
    sampleTags,
    popular: popular || undefined,
  };
}

/** @type {HashtagCategory[]} */
export const HASHTAG_CATEGORIES = [
  category('travel', 'Travel', ['#travel', '#traveller', '#vacation', '#explore', '#travelgram'], true),
  category('food', 'Food', ['#food', '#foodie', '#yummy', '#foodlover', '#foodporn'], true),
  category('fitness', 'Fitness', ['#fitness', '#fitlife', '#workout', '#gym', '#fitnessmotivation'], true),
  category('fashion', 'Fashion', ['#fashion', '#style', '#ootd', '#fashionista', '#outfit'], true),
  category('photography', 'Photography', ['#photography', '#photooftheday', '#photo', '#camera', '#photographer'], true),
  category('gaming', 'Gaming', ['#gaming', '#gamer', '#videogames', '#gameplay', '#esports'], true),
  category('beauty', 'Beauty', ['#beauty', '#makeup', '#skincare', '#glam', '#beautyblogger'], true),
  category('reels', 'Reels', ['#reels', '#reelsinstagram', '#viral', '#trending', '#reelitfeelit'], true),
  category('christmas', 'Christmas', ['#christmas', '#xmas', '#holidays', '#festive', '#christmastree']),
  category('gym', 'Gym', ['#gym', '#gymlife', '#fitness', '#training', '#gymmotivation']),
  category('yoga', 'Yoga', ['#yoga', '#yogalife', '#mindfulness', '#wellness', '#yogapractice']),
  category('funny', 'Funny', ['#funny', '#humor', '#lol', '#comedy', '#funnyvideos']),
  category('dog', 'Dog', ['#dog', '#dogsofinstagram', '#puppy', '#doglover', '#dogstagram']),
  category('cat', 'Cat', ['#cat', '#catsofinstagram', '#kitten', '#catlover', '#catlife']),
  category('nature', 'Nature', ['#nature', '#naturephotography', '#outdoors', '#landscape', '#naturelovers']),
  category('love', 'Love', ['#love', '#couple', '#romance', '#lovestory', '#lovequotes']),
  category('birthday', 'Birthday', ['#birthday', '#happybirthday', '#bday', '#celebration', '#birthdayparty']),
  category('wedding', 'Wedding', ['#wedding', '#bride', '#weddingday', '#love', '#weddingphotography']),
  category('meme', 'Meme', ['#meme', '#memes', '#funny', '#viral', '#memesdaily']),
  category('real-estate', 'Real estate', ['#realestate', '#home', '#property', '#realtor', '#realestateagent']),
  category('vegan', 'Vegan', ['#vegan', '#plantbased', '#veganfood', '#healthy', '#vegansofig']),
  category('makeup', 'Makeup', ['#makeup', '#mua', '#makeuptutorial', '#beauty', '#makeuplover']),
  category('selfie', 'Selfie', ['#selfie', '#selfietime', '#me', '#portrait', '#selfiegram']),
  category('summer', 'Summer', ['#summer', '#summervibes', '#sun', '#beach', '#summerdays']),
  category('sunset', 'Sunset', ['#sunset', '#goldenhour', '#sky', '#nature', '#sunsetlovers']),
  category('beach', 'Beach', ['#beach', '#ocean', '#seaside', '#vacation', '#beachlife']),
  category('music', 'Music', ['#music', '#musician', '#song', '#newmusic', '#musiclover']),
  category('motivation', 'Motivation', ['#motivation', '#inspiration', '#mindset', '#goals', '#motivational']),
  category('coffee', 'Coffee', ['#coffee', '#coffeetime', '#cafe', '#latte', '#coffeelover']),
  category('art', 'Art', ['#art', '#artist', '#artwork', '#creative', '#artoftheday']),
  category('jewelry', 'Jewelry', ['#jewelry', '#accessories', '#handmade', '#fashion', '#jewelrydesign']),
  category('workout', 'Workout', ['#workout', '#fitness', '#training', '#exercise', '#workoutmotivation']),
  category('best-friend', 'Best friend', ['#bestfriend', '#bff', '#friendship', '#friends', '#besties']),
  category('fox-quotes', 'Fox Quotes', ['#fox', '#quotes', '#wisdom', '#inspiration', '#quotestoliveby']),
  category('portrait', 'Portrait', ['#portrait', '#portraitphotography', '#model', '#face', '#portraits']),
  category('cool', 'Cool', ['#cool', '#style', '#vibes', '#aesthetic', '#coolkids']),
  category('design', 'Design', ['#design', '#graphicdesign', '#creative', '#designer', '#designinspiration']),
  category('health', 'Health', ['#health', '#healthy', '#wellness', '#selfcare', '#healthylifestyle']),
  category('party', 'Party', ['#party', '#celebration', '#nightout', '#fun', '#partynight']),
  category('inspirational', 'Inspirational', ['#inspirational', '#quotes', '#motivation', '#positive', '#inspiration']),
  category('anime', 'Anime', ['#anime', '#manga', '#otaku', '#animeart', '#animefan']),
  category('vintage', 'Vintage', ['#vintage', '#retro', '#classic', '#nostalgia', '#vintagestyle']),
  category('streetwear', 'Streetwear', ['#streetwear', '#streetstyle', '#sneakers', '#urban', '#streetfashion']),
  category('festival', 'Festival', ['#festival', '#musicfestival', '#livemusic', '#vibes', '#festivalseason']),
  category('architecture', 'Architecture', ['#architecture', '#design', '#building', '#urban', '#archilovers']),
  category('dancing', 'Dancing', ['#dancing', '#dance', '#dancer', '#choreography', '#dancelife']),
  category('tatto', 'Tattoo', ['#tattoo', '#ink', '#tattooart', '#bodyart', '#tattooed']),
  category('books', 'Books', ['#books', '#bookstagram', '#reading', '#booklover', '#bookworm']),
  category('night', 'Night', ['#night', '#nightphotography', '#citylights', '#dark', '#nightlife']),
  category('yummy', 'Yummy', ['#yummy', '#delicious', '#foodie', '#tasty', '#foodgasm']),
  category('baby', 'Baby', ['#baby', '#newborn', '#babylove', '#cute', '#babygirl']),
  category('girls', 'Girls', ['#girls', '#girl', '#girlpower', '#style', '#girlsnight']),
  category('family', 'Family', ['#family', '#familytime', '#love', '#parents', '#familyfirst']),
  category('black', 'Black', ['#black', '#blackaesthetic', '#monochrome', '#dark', '#blackandwhite']),
  category('red', 'Red', ['#red', '#redaesthetic', '#color', '#vibes', '#redlipstick']),
  category('smile', 'Smile', ['#smile', '#happy', '#positivity', '#joy', '#smilemore']),
  category('died', 'Died', ['#rip', '#memorial', '#remember', '#tribute', '#restinpeace']),
  category('eyes', 'Eyes', ['#eyes', '#eyemakeup', '#portrait', '#beauty', '#eyeshadow']),
  category('puppy', 'Puppy', ['#puppy', '#puppylove', '#dog', '#cute', '#puppiesofinstagram']),
  category('fish', 'Fish', ['#fish', '#aquarium', '#fishing', '#sea', '#fishtank']),
  category('pet', 'Pet', ['#pet', '#pets', '#petlover', '#animals', '#petstagram']),
  category('animal', 'Animal', ['#animal', '#animals', '#wildlife', '#nature', '#animalsofinstagram']),
  category('sushi', 'Sushi', ['#sushi', '#japanesefood', '#foodie', '#dinner', '#sushilover']),
  category('pizza', 'Pizza', ['#pizza', '#pizzalover', '#food', '#italianfood', '#pizzatime']),
  category('chef', 'Chef', ['#chef', '#cooking', '#foodie', '#kitchen', '#cheflife']),
  category('colour', 'Colour', ['#colour', '#colorful', '#aesthetic', '#vibes', '#colours']),
  category('white', 'White', ['#white', '#whiteaesthetic', '#minimal', '#clean', '#whitewall']),
  category('green', 'Green', ['#green', '#nature', '#eco', '#plants', '#greenery']),
  category('blue', 'Blue', ['#blue', '#blueaesthetic', '#ocean', '#sky', '#bluesky']),
  category('life', 'Life', ['#life', '#lifestyle', '#daily', '#moments', '#lifeisgood']),
  category('flower', 'Flower', ['#flower', '#flowers', '#floral', '#nature', '#flowerstagram']),
  category('video', 'Video', ['#video', '#videography', '#content', '#creator', '#videooftheday']),
  category('sport', 'Sport', ['#sport', '#sports', '#athlete', '#fitness', '#sportslife']),
  category('kid', 'Kid', ['#kid', '#kids', '#childhood', '#family', '#kidsofinstagram']),
  category('news', 'News', ['#news', '#breaking', '#update', '#media', '#currentevents']),
  category('bag', 'Bag', ['#bag', '#handbag', '#fashion', '#accessories', '#baglover']),
  category('dress', 'Dress', ['#dress', '#fashion', '#outfit', '#style', '#dressup']),
  category('sky', 'Sky', ['#sky', '#clouds', '#bluesky', '#nature', '#skylovers']),
  category('happy', 'Happy', ['#happy', '#happiness', '#joy', '#goodvibes', '#happyday']),
  category('pink', 'Pink', ['#pink', '#pinkaesthetic', '#cute', '#pastel', '#pinkvibes']),
  category('bike', 'Bike', ['#bike', '#cycling', '#bicycle', '#ride', '#bikelife']),
  category('drink', 'Drink', ['#drink', '#cocktail', '#beverage', '#bar', '#drinkstagram']),
  category('shop', 'Shop', ['#shop', '#shopping', '#store', '#retail', '#shoplocal']),
  category('deco-decor', 'Deco Decor', ['#decor', '#homedecor', '#interior', '#design', '#homedesign']),
  category('tutorial', 'Tutorial', ['#tutorial', '#howto', '#tips', '#learn', '#tutorials']),
  category('skin', 'Skin', ['#skin', '#skincare', '#glow', '#beauty', '#skincareroutine']),
  category('rainbow', 'Rainbow', ['#rainbow', '#colorful', '#pride', '#vibes', '#rainbowcolors']),
  category('disney', 'Disney', ['#disney', '#disneyland', '#magic', '#fantasy', '#disneyworld']),
  category('chocolate', 'Chocolate', ['#chocolate', '#dessert', '#sweet', '#food', '#chocolatelover']),
  category('lipstick', 'Lipstick', ['#lipstick', '#makeup', '#beauty', '#lips', '#lipsticklover']),
  category('coach', 'Coach', ['#coach', '#coaching', '#mentor', '#success', '#lifecoach']),
  category('retro', 'Retro', ['#retro', '#vintage', '#80s', '#90s', '#retrowave']),
  category('hair', 'Hair', ['#hair', '#hairstyle', '#hairgoals', '#beauty', '#haircolor']),
  category('home', 'Home', ['#home', '#homedecor', '#cozy', '#interior', '#homestyle']),
  category('interior', 'Interior', ['#interior', '#interiordesign', '#decor', '#home', '#interiorinspo']),
  category('look', 'Look', ['#look', '#outfit', '#style', '#fashion', '#lookoftheday']),
  category('jokeday', 'Jokeday', ['#joke', '#funny', '#humor', '#comedy', '#jokes']),
  category('friendship', 'Friendship', ['#friendship', '#friends', '#bff', '#besties', '#friendshipgoals']),
];

export function getCategoryCollageImages(slug) {
  return [
    `/hashtag-categories/${slug}-1.webp`,
    `/hashtag-categories/${slug}-2.webp`,
  ];
}
